version: "2"
services:
  app:
    container_name: "app"
    restart: always
    build: .
    environment:
      - PORT=3000
      - NODE_ENV=production
    ports:
      - "3000:3000"
    command: npm start